-- -- Drop existing foreign key constraint if it exists
-- ALTER TABLE post DROP FOREIGN KEY IF EXISTS FK72mt33dhhs48hf9gcqrq4fxte;
--
-- -- Dummy Users
-- INSERT INTO User (id, name, email, password, about)
-- VALUES (1, 'John Doe', 'john@example.com', 'password123', 'About John Doe');
-- INSERT INTO User (id, name, email, password, about)
-- VALUES (2, 'Jane Smith', 'jane@example.com', 'password456', 'About Jane Smith');
-- INSERT INTO User (id, name, email, password, about)
-- VALUES (3, 'David Johnson', 'david@example.com', 'password789', 'About David Johnson');
--
-- -- Dummy Roles
-- INSERT INTO Role (id, roleName)
-- VALUES (1, 'ROLE_ADMIN');
-- INSERT INTO Role (id, roleName)
-- VALUES (2, 'ROLE_USER');
--
-- -- Dummy Posts
-- INSERT INTO Post (id, content, user_id)
-- VALUES (1, 'Post 1 content', 1);
-- INSERT INTO Post (id, content, user_id)
-- VALUES (2, 'Post 2 content', 2);
-- INSERT INTO Post (id, content, user_id)
-- VALUES (3, 'Post 3 content', 3);
--
-- -- Dummy Comments
-- INSERT INTO Comment (id, Content)
-- VALUES (1, 'Comment 1');
-- INSERT INTO Comment (id, Content)
-- VALUES (2, 'Comment 2');
-- INSERT INTO Comment (id, Content)
-- VALUES (3, 'Comment 3');
--
-- -- User-Role Mapping
-- INSERT INTO user_role (user, role)
-- VALUES (1, 1);
-- INSERT INTO user_role (user, role)
-- VALUES (2, 2);
-- INSERT INTO user_role (user, role)
-- VALUES (3, 2);